/*

	2 may. 2019
*/


#include "../Headers/libRosalind.h"

void DNA(void){
    char *s="GCCACGGAGATGATTTGAGTAAACGTCTACCCAAGGGTGGCTACTGTTTTACCCTCTTTTAGGAGGTCAGCCGGCTCTCAAGCATGCTATCCGTGAGCGCATTTATCGTGACAAACTACACCTCGATTCGGATTGGAAGCCATTCCACTCAGCGTGCACATAAACCGCGATTTGTCACAACAGACGGAAGCGCAGTTTTAAGAGTTAGTACAGCGGGAGTCCGAACTTTTGCCTGATAAATGATTGGAATGGGATTCCCTAATGAGTCTATCACCGCAATTTATCAACTTTCGGAGTAGCACCGTCGAAACTTGTATGGTACGCACCGTCGGTTAAACCCTACTGCTACGATACTTCGAGTTTTATGCCCCACACTACTCTAACTCGCATATAGAAGGAATTTGATTTCGTTGATCATCTCGTAGGACGGTTTTCTCGTAGATACCGCCGTCTTGGTTATAAGAAATGGCGGCCACTCTAGCCGTCAGATTTCAGTTATGCGGGACACTCGTTTTTATGACTAGTTTTGAGGAGTGATTACAATAAGATTGTTATAGCGGGATGGAGAGTGCGGATGTTCACAAAATTTACGACATGTTTGTAAACTGAGCTTTACTGCTCCTTCTTGGATGCTCTCGTTGGCACCTCGCTAACAGAGAACGCCGCATCCTCCGTCCTACATCATTGCCCCTGAAGAGTGCCAGCCTGCCTATTCATGGATAAGGACCTCGATATACGCTCACTGTCCACGGGCAGACTCAAATCAGGTAACCCCCGATAAGTCTGATAGCTGGACCGATCGGCAGCAGCAGTTACCGTAGATTGAACTTAATTGTTAGTCACCGTCGTCGCGGCAACCATTGTTACCTGGTGTCAGACGCCGGACTACCCGCTCGATAACGTTACACTCACTGCACGAGGTAGCCCGTAGGCTCACGTAGTTCGACCGCAGCCGCAGCGGATGACTAGTGAATGGGCG";
    char symb[4]={'A','C','G','T'};
    int count[4]={0};
    for(int i=0;i<strlen(s);i++){
    	for(int j=0;j<4;j++){
    		if(s[i]==symb[j]) count[j]++;
    	}
    }
    printf("Problem DNA - Result: %d %d %d %d.\n", count[0],count[1],count[2],count[3]);
    return;
}
