/*

	2 may. 2019
*/


#include "libRosalind.h"

void P0001(void){
    time_t tInit=clock();
    char *s="GTCCCACGCTGTTAGCTATCGCGCATCTGGCATATAGGTGAGATGCTTTGTTAATTCGTTCACTCGCACATATACGTCGTGGTGCAAGTGTGTCAGTTTAGTATCCTACCGTCGAAGGGGATAGTGATGTACCATTCGTGCGTTCTGTAGGGGCTTACTCCCGCCAGTACGCGCGCAGCCGGACCAAACATCCAATTGTAAAGCTTAGTGTATGCTATGGGCACTGGTTAGCGCTTTCCCGTATCCACACCCAGAATCTGGACTGGGGTCCCCGCGTGTGCTTGCCGGTAATACGTTCCTTCGCAGCCACCTTCTACATATGCACTTTGAAGGGATACGTTGCTTTGTCTTGTGGATAGCTTTATGATCGATGGGAATAGCAAATGCCTATACACGATAGCGTATCGAGAGTCCACTTAAGGTCTGTGCAGTACTGCCAAAAGGGCAAAGCCAGTAAGAAGAACCCTCTTCATTACGAACGCTGAACGTACGTAGTGATCTACCGAACGCGCGACCCGAAAATTCTCGGTTGAGCCATGTTCCGGCCGATGGTACCGAAACTACGCCCAATGCTTAACCGGGCATCGCTGTGTCGACGACCGGGCAGTCCTTGTGGGGCCTCTTGATGAGCTCGGGCAAGATAATTCCCCGAAGGCAGTCAAGGCACGCGCAGTCCTTGACAGTCGGACAAGTCGGAAAACAGCTAACTGCTACGATGATTTATAACGTAAAAGTCGTAGGACCGAGTCTCGGCGGGTCGGCACGTAGTCGCTTTATCTCACCGACGCAGTCATTGTTCAACTCGGCTAAGGCGCATTATAAGTTTAAATTATGATCCCCAAGCCCTACTTTTGTGCTCGCAAACCCTTCAGGTATTTGGCATGCCTGGAGGTTTTTCACAATTGTTATTGCAAGATTGAAGTACGACTTAGCAGGGCCAACTGTAAGAAAG";
    char symb[4]={'A','C','G','T'};
    int count[4]={0};
    for(int i=0;i<strlen(s);i++){
    	for(int j=0;j<4;j++){
    		if(s[i]==symb[j]) count[j]++;
    	}
    }
    time_t tEnd=clock();
    printf("Problem 0001 - Result: %d %d %d %d. Elapsed Time: %.6f\n", count[0],count[1],count[2],count[3],(double) (tEnd-tInit)/CLOCKS_PER_SEC);
    return;
}
