/*

	3 may. 2019
 */

#include "libRosalind.h"
#define LIMIT 1000
void REVC(void){
	char *s="CCGCCGAGTCAGCTTGTAGTCGACTTGCGCGGCACCGGCTTCTACGAGGCGCAGTAATGACGATATGCAGTGAGAGAGCGATCTGGCCCCCGACAACAGGCGTATCAAGTCTGTCATCAAGGTAATAGCTGTCTAACCTTTGTGCTGATTTTCGTTCCTGGTGCCCTCGGAGAGAAGTGTCTCGATTCAGATAATGCAAACGTCGGCCGATCACCCATTTGGAACGCCTTTGAAGTTTTTGGCCTATGAGAGGTTGCGACTTTCTTATTTGGGCAGTAGGTATCTTTGTCAATCGAAATGAAGCCTTGTTGGGCCATCTGTTGAGGGGTGGACAGGCTTCTAACTCACCAGGCCTGAGGGATCTAGTCTAGATGCGAGCTCCCTCCGGGACAGGCCGGTTCTAGGATCCTGTCGTGTACCCCGGATTACACGTCTAAGTCTTGTACATCAAGTTCGGTCATGATCGTTGGAGTACATGTGTATACCATTTTCTTCTATGTCCCGAACCGCGCGGAGAGTGTTATGATAACGCCGGAGGCAATCCTGCTGCGGACCCTACCACCCCGGTCCAGGAAAATTTGAGAGTCTTCTATGCTCCTGGGCTTCGATTCATGCACCACACGACGAAAGACAAGCTCGTTCGCGGGCTAGACTTCGTTTTAGGTCTCCTGCGGGTGGGCGCATCAACCGAGAGCAATCGGATCGCTTCCTCGCGTGTAAATGTACCGTGCCTCGACGGATCCGCGCATCATTGAGCAGAGACAGCATCAATGGGCAGCACATACGTGCCATCAAGGGCTGACATCGCTTAGAGAATCATCTAACTCAGAGATTAGGAATAACACTGAGAAGTGCACGGTTCGTCTCGATGCGATGACAGTCTTGCCGTAATAAACATTAAACTAGTACCCGACTGCGTTATTTCTGAGATTATAATCCAAGCAACATGGGCACCGGATAGTGGATTAGGAAGCGAGCGAGCACT";
	char resp[LIMIT]={'\0'};
	int len=strlen(s)-1;
	for(int i=len;i>=0;i--){
		switch(s[i]){
			case 'T':
				resp[len-i]='A';
				break;
			case 'A':
				resp[len-i]='T';
				break;
			case 'C':
				resp[len-i]='G';
				break;
			case 'G':
				resp[len-i]='C';
				break;
		}
	}
	printf("Problem REVC - Result: %s.\n", resp);
	return;
}
