/*

	3 may. 2019
*/

#include "libRosalind.h"

void RNA(void){
    time_t tInit=clock();
    char s[1500]="GGAACGTCGTTCCCTTAAGAGTGATTGTGCAGAATGCGGAGATACGCGGGTCCACCTGGGTAATTACCGTCAACGTATACTCCTGACAACCGTAAGTATTTGCTATATAGCGTCCCACTGACAGCTATTCATTTGTATTTCCCGAGCTATGTGAACGCTCTAAGAGTCGGATGAGGCCCAAGAGAATTACTATTAACCGTATCATAAAAACCCAACGAAGCACTCTGTTCGACGGGTTTCCATCGGAAAATTGGAATCCAGGGGGGCATCGAGAAGAGCGTAATTAAAAAAGGAGCGTAGGCAGCAGTCCGGGTTAACATTTGTCGGATATCCTAGGATGTGACACCTGTTCAATTGGCTGGCTGAACAGCAAAATTTCTGTTGGTACGAACTTGGCTCGTTCCTCAACTATATAGGGTTTCAACTAAACGCGACCCTAGGCCTCAATGCCGTAGCTCCCGATGTGGCACAGTACAAAGCTTGTCCTTTAGGTGCAATAGGAAGACCCGCAACTGGATTGAACACGCATTGATAGGCGACTGTCACGGATCCATCACTCCTCGGGCCGGACCTACGCTTCCGACAAGGAACCTGTGCTCCCCCGGGGTCTTCCGCGTTGATTTTACGCACTGGCGCCCGTTGTCACATCTTCTGCAGGGACGCTTCCCTGCCTCACTGGAAATGGCGCTCTCATTTCTAGGTTAAACGACTCGGAGGCTCATTTATTGTGCAGGGCATATCGTGATCTTGAAAGGATACAAGTTCGGTTGATGTGGTCACGCTAATACTGACGTCGTGGCTGCTCATACGAACGTCGGATCAGCGCGTTGTCCAATATAAAATTGCATCTATAGCTAGCCAGTTCTCCACCGTTGGTGTTTCCTGTAGTTATAAATGGAATGCACAGAATAAAAGTGGAGTGAGTGCAGATGAGATACAACAG";
    for(int i=0;i<strlen(s);i++){
    	if(s[i]=='T') s[i]='U';
    }
    time_t tEnd=clock();
    printf("Problem RNA- Result: %s. Elapsed Time: %.6f\n", s,(double) (tEnd-tInit)/CLOCKS_PER_SEC);
    return;
}
