/*
	Rosalind Project
	SUBS.c
	4 may. 2019-13:31:17
	L
*/

#include "libRosalind.h"

void SUBS(void){
	char *s="CCGCGGACCGCGGATCCGCGGACTGCCGCGGAATGCCGCGGACCGCGGAAGATGTGCCCGCGGACACCCGCGGACCATACTTCCGCGGAAGGCCGCGGACCGCCGCGGACCGCGGACCGCGGACCGCACCCGCGGACACCGCGGATCCGCGGACACCGCGGATTCCGCGGAGGACCGCGGATTCCGCGGAGTTTCCGCACCGCGGACCCGCGGACGCCGCGGAACCCGCGGACCCGCGGACTCTTACTACATAGCCGCGGACCGCGGACATACCGCGGACAGCGGTTCCGCGGACCGCGGACCGCGGAACCGCGGAGGCCGCGGACTCCGCGGAGACCCCCGCGGATTTCCGCGGATTCCGCGGACCGCGGACACGCAGACCGCGGAAGTCTCCGCGGAATCCGCGGATGCCGCGGACCGCGGACCGCGGAACCGCGGAGCTCCGCGGAGTAGCCCGCGGACGCCGCGGACCGCGGAACCCGCGGATCCCGCGGAACCCCCGCGGACTCCGCGGATCCGCGGACCTCGCCGCGGACAACCGCGGATCCGCGGACTGCCGCGGACCGCGGAGCCGCGGACCCGCGGACTGTGCTCACGCCGCGGACCGCGGAGCTTGGCCCGCGGATGGCCGCGGATATCCGCGGAGCACCTACTTCCGCGGACCCTTTCCGCGGACTCCGCGGAGGGCCGCGGAACCGCGGATTCCGCGGACCTTCCGCGGATGCATCCCGCGGACCGCGGAGCCGCGGATCCGCGGAAGGACCCGCGGAGTTCCGCGGACCCCGCGGAACACCGCGGACCGCGGATATCATGCGAACTCCGCGGACAGACCGCGGAGAGCCGCGGAAGATCCGCGGAGCAAGCCCGCGGACCGCGGACCTACCGCGGACCGCGGAACCGCGGACCGCGGATGGCCGCGGACCGCGGAGCCCGCGGAAAGCCCTACTGATGCCGCGGATCCCGCGGA";
	char *t="CCGCGGACC";
	int lenS=strlen(s), lenT=strlen(t);
	bool find=FALSE;
	if(lenS>=lenT){
		for(int i=0;i<lenS;i++){
			find=FALSE;
			for(int j=0, k=i;j<lenT;j++,k++){
				if(s[k]!=t[j]){
					find=FALSE;
					break;
				}else{
					find=TRUE;
				}
			}
			if(find==TRUE) printf("%d ",i+1);
		}
	}
	return;
}
